activate_scene:
    name: Activate Scene
    description: Activates the specified scene.
    fields:
        zone:
            name: Zone
            description: Selected Zone
            required: true
            advanced: false
            example: "bedroom"
        scene:
            name: Scene
            description: Selected Scene
            required: true
            advanced: false
            example: "off"

disable_entity:
    name: Disable Entity
    description: Disable an entity of a room to exclude it from updating.
    target:

enable_entity:
    name: Enable Entity
    description: Re-enable an entity that got disabled.
    target:

reset_scene:
    name: Reset Scene
    description: Reset a scene to its default settings.
    target: